#!/usr/bin/env python3
"""Find (and with --apply delete) the scratch files that pile up while we work, on the Mac and on the Pi.

    python tools/g2_cleanup.py            dry run: list what would be deleted and what needs a decision (default)
    python tools/g2_cleanup.py --apply    delete the "delete" list by exact path (never a wildcard), then clean the Pi's stray files
    python tools/g2_cleanup.py --check    fast, git status only, no ssh; prints one reminder line and only when something is left (used by the Claude Code hook)
    python tools/g2_cleanup.py --no-pi    skip the Pi check

Classes of finding:
  DELETE   scratch by pattern (comparison copies, intermediate report folders, probe output, *.bak, __pycache__ strays) -- removed by --apply
  DECIDE   untracked files that are not scratch: commit them (git add by exact path) or delete them; never deleted automatically
  PI       files on the Pi's trained/ folder other than Release_Candidate*_ppo.onnx(.json) -- removed by --apply over ssh ($G2_PI)
Never touched (protected): anything tracked by git, checkpoints, run console logs, candidate exports (*_ppo.onnx*, except an untracked copy byte-identical to a tracked
Release_Candidate*_ppo.onnx, which is a leftover of the promote step and is listed under DELETE), trained/v3_world2, V3 report caches.
"""
import argparse
import fnmatch
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TRAINED = "rl_training/opencat-gym/trained"

# Scratch patterns (relative to the repo root, fnmatch on the full path). Anything matching is safe to delete: it is regenerated by the tool that made it.
SCRATCH = [
    f"{TRAINED}/*_at*M_ppo.zip",          # paired_compare.py's per-checkpoint comparison copy
    f"{TRAINED}/v4_report_*",             # intermediate-checkpoint report folders
    f"{TRAINED}/zz_*",                    # one-off probe output
    f"{TRAINED}/*.out",
    "rl_training/opencat-gym/eval_frames", "rl_training/opencat-gym/frames_wkf",     # frame dumps of evaluate_policy.py --frames-dir / verify_wkf_reference.py --render
    "rl_training/opencat-gym/robustness_sweep.json",                             # robustness_sweep.py's default output file
    "rl_training/opencat-gym/.carpet_tex_cache.png",                             # watch.py rebuilds this texture cache when it is missing
    "*.bak", "*.orig", "*.rej", "*.tmp",
    "*/.DS_Store", ".DS_Store",
]
# Never delete, whatever the patterns say.
PROTECT = [f"{TRAINED}/v3_world2", f"{TRAINED}/checkpoints/*", f"{TRAINED}/*_ppo.onnx*", f"{TRAINED}/*_console.log", f"{TRAINED}/phase_v4.log"]
PI_KEEP = re.compile(r"^Release_Candidate[^ /]*_ppo\.onnx(\.json)?$")
PI_TRAINED = "bittleX/rl_training/opencat-gym/trained"


def git(*args):
    return subprocess.run(["git", "-C", ROOT, *args], capture_output=True, text=True).stdout


def matches(path, patterns):
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def untracked():
    """Untracked, non-ignored paths (git folds a whole new folder into one 'dir/' entry)."""
    return [l[3:] for l in git("status", "--porcelain", "-uall").splitlines() if l.startswith("?? ")]


def ignored_scratch():
    """Ignored files that still match a scratch pattern (the big ones in trained/)."""
    out = git("ls-files", "--others", "--ignored", "--exclude-standard", "--directory").splitlines()
    return [p.rstrip("/") for p in out if matches(p.rstrip("/"), SCRATCH) and not matches(p.rstrip("/"), PROTECT)]


def _sha(path):
    import hashlib
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def duplicate_candidates():
    """Exported candidates (`<name>cand_ppo.onnx` + its sidecar) that are byte-identical to a tracked Release_Candidate*_ppo.onnx: the promote step
    copied them, so the extra copy is scratch. A candidate that was never promoted is NOT here (it is a DECIDE: the user keeps or deletes it)."""
    tracked = [t for t in git("ls-files", TRAINED).splitlines() if re.search(r"/Release_Candidate[^/]*_ppo\.onnx$", t)]
    if not tracked:
        return []
    hashes = {_sha(os.path.join(ROOT, t)) for t in tracked}
    out = []
    for line in git("status", "--porcelain", "--ignored", "-uall", "--", TRAINED).splitlines():
        path = line[3:]
        if re.search(r"/[^/]*cand_ppo\.onnx$", path) and os.path.exists(os.path.join(ROOT, path)) and _sha(os.path.join(ROOT, path)) in hashes:
            out += [q for q in (path, path + ".json") if os.path.lexists(os.path.join(ROOT, q))]
    return out


def classify():
    dups = duplicate_candidates()
    delete, decide = list(dups), []
    for p in untracked():
        if p in dups:
            continue
        if matches(p, PROTECT):
            if p.startswith(TRAINED + "/") and re.search(r"_ppo\.onnx(\.json)?$", p):
                decide.append(p)                      # an exported candidate nobody committed or promoted: protected from deletion, but the user decides
            continue
        (delete if matches(p, SCRATCH) else decide).append(p)
    delete += [p for p in ignored_scratch() if p not in delete]
    return sorted(delete), sorted(decide)


def pi_stray():
    pi = os.environ.get("G2_PI")
    if not pi:
        return None, "G2_PI not set"
    r = subprocess.run(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=5", pi, f"ls -1 {PI_TRAINED} 2>/dev/null; echo ---; df -h / | tail -1"], capture_output=True, text=True)
    if r.returncode != 0:
        return None, "the Pi does not answer"
    names, _, disk = r.stdout.partition("---\n")
    return [n for n in names.splitlines() if n and not PI_KEEP.match(n)], disk.strip()


def rm(path):
    full = os.path.join(ROOT, path)
    if os.path.isdir(full) and not os.path.islink(full):
        import shutil
        shutil.rmtree(full)
    elif os.path.lexists(full):
        os.remove(full)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--no-pi", action="store_true")
    a = ap.parse_args()

    delete, decide = classify()
    if a.check:
        if delete or decide:
            print(f"cleanup reminder: {len(delete)} scratch file(s) to delete, {len(decide)} untracked file(s) to commit or delete. "
                  f"Run `python tools/g2_cleanup.py` (dry run) and clean up before reporting done.")
        return 0

    print(f"DELETE ({len(delete)}):" + ("" if delete else " none"))
    for p in delete:
        print(f"  {p}")
    print(f"DECIDE ({len(decide)}): untracked, not scratch -- commit by exact path or delete" + ("" if decide else " -- none"))
    for p in decide:
        print(f"  {p}")

    stray = None
    if not a.no_pi:
        stray, disk = pi_stray()
        if stray is None:
            print(f"PI: skipped ({disk})")
        else:
            print(f"PI ({len(stray)} stray in {PI_TRAINED}; disk: {disk}):" + ("" if stray else " clean"))
            for n in stray:
                print(f"  {n}")

    if not a.apply:
        if delete or decide or stray:
            print("\n(dry run) re-run with --apply to delete the DELETE and PI lists.")
        return 0

    for p in delete:
        rm(p)
        print(f"deleted {p}")
    if stray:
        # exact names only, quoted; GNU rm on the Pi
        names = " ".join(f"'{n}'" for n in stray if "'" not in n and "/" not in n)
        r = subprocess.run(["ssh", os.environ["G2_PI"], f"cd {PI_TRAINED} && rm -rf -- {names}"], capture_output=True, text=True)
        print("Pi cleaned" if r.returncode == 0 else f"Pi cleanup failed: {r.stderr.strip()}")
    if decide:
        print(f"{len(decide)} untracked file(s) still need a decision (listed above).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
