#!/usr/bin/env python3
"""Generate docs/backlog.md — the index of open work by ID — from the item headings. Stdlib only.

    python tools/gen_backlog.py           # rewrite docs/backlog.md
    python tools/gen_backlog.py --check   # exit 1 if docs/backlog.md is out of date (the doc checker runs this)

Single source of truth: each item's heading in its own file (docs/rl/hardware-gated-backlog.md `H#`,
docs/rl/robustness-backlog.md `R#`, docs/behavior-ideas.md `B#`) carries its status icon/tag. The index is generated from those
headings, so it cannot drift: change a status in the heading, then re-run this (or let the pre-commit hook tell you).
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from check_docs import slug  # noqa: E402

SOURCES = [
    ("Hardware-gated training (waiting on real-robot data)", "docs/rl/hardware-gated-backlog.md",
     re.compile(r"^## (H\d+) — (.*?)(?:\s{2,}(.*))?$")),
    ("Robustness ablations", "docs/rl/robustness-backlog.md",
     re.compile(r"^### (R\d+) · (.*?) — (.*)$")),
    ("Behavior ideas", "docs/behavior-ideas.md",
     re.compile(r"^### (B\d+[a-z]?) — (.*?)(?:\s{2,}(?:— )?(.*))?$")),
]
LEGEND = {
    "Hardware-gated training (waiting on real-robot data)":
        "🔴 blocked on hardware · 🟡 partial sim work possible now · ⚪ may never be needed · 🟢 confirmed need",
    "Robustness ablations": "`TODO`, `LATER`, `DEFERRED`, `DROPPED`, `EXPLORE`, `REVISIT` — as written in each heading",
    "Behavior ideas": "🔴 hardware/camera-gated · 🟡 partial · ⚪ low priority · 🟢 confirmed · BUILT/WIRED as noted; no marker = idea, not started",
}


def build():
    out = ["# Backlog — open work by ID", "",
           "> **Generated** by `tools/gen_backlog.py` from the item headings. Do not edit this file: change an item's status in its own",
           "> heading, then re-run the script (the pre-commit doc check tells you when it is stale). Current priorities: [`STATUS.md`](STATUS.md).", ""]
    for title, path, rx in SOURCES:
        out += [f"## {title}", "", f"Status key: {LEGEND[title]}. Source: [`{os.path.basename(path)}`]({path[5:] if path.startswith('docs/') else '../' + path}).", "",
                "| ID | Item | Status |", "|---|---|---|"]
        for line in open(os.path.join(ROOT, path), encoding="utf-8").read().splitlines():
            m = rx.match(line)
            if not m:
                continue
            iid, item, status = m.group(1), m.group(2).strip(), (m.group(3) or "").strip()
            status = re.sub(r"\s+", " ", status).strip(" —") or "—"
            heading_text = line.lstrip("# ").strip()
            link = (path[5:] if path.startswith("docs/") else "../" + path) + "#" + slug(heading_text)
            out.append(f"| [{iid}]({link}) | {item.replace('|', '/')} | {status.replace('|', '/')} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    target = os.path.join(ROOT, "docs", "backlog.md")
    text = build()
    if "--check" in sys.argv:
        cur = open(target).read() if os.path.exists(target) else ""
        if cur != text:
            print("docs/backlog.md is out of date -- run: python tools/gen_backlog.py")
            return 1
        return 0
    open(target, "w").write(text)
    print(f"wrote {target} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
